### ISSUE TITLE
Why are error and accuracy not returned?

### ISSUE THREAD

**Issue by abhisheksoni27** [mljs/knn#1]

**Comment by maasencioh** [comment]
Hello @abhisheksoni27, currently any of this metrics are implemented in this package, but those are nice features request

**Comment by abhisheksoni27** [comment]
@maasencioh Thanks. Also, what about a method that automatically chooses the best k?

**Comment by JeffersonH44** [comment]
Hello @abhisheksoni27, when you mean error you want the sum of all distances of the nearest neighboors to the point that I want to predict?

**Comment by abhisheksoni27** [comment]
@JeffersonH44 Error here refers to the `number of misclassifications / total number of cases`.

An easy way to figure that out might be to use the `knn.run()` method on an `array` of test data, then check how many misclassifications were there in it, and return the ratio.

**Comment by targos** [comment]
We have developped a package for cross validation and I think this is where the error and accuracy should be computed. Here is the repo: https://github.com/mljs/cross-validation
The confusion matrix would be enough to compute this and I have an open issue about moving it out to a standalone package: https://github.com/mljs/cross-validation/issues/2

**Comment by stropitek** [comment]
@abhisheksoni27 I just published `ml-confusion-matrix`
Using it with knn would look something like:
```js
const knn = new KNN(trainData, trainLabels);
const predictedLabels = knn.predict(testData);
const CM = ConfusionMatrix.fromLabels(testLabels, predictedLabels);
console.log(CM.accuracy);
```
In the future ConfusionMatrix will allow to compute interesting derivatives like true positive, true negative, false positive, false negative.

**Comment by abhisheksoni27** [comment]
@stropitek Brilliant! :100: 

Thanks for that module. Interesting features to come. :tada:

**Comment by abhisheksoni27** [comment]
Closing because [ml/confusion-matrix](https://github.com/mljs/confusion-matrix) is here.
