### ISSUE TITLE
Default k value

### ISSUE THREAD

**Issue by stropitek** [mljs/knn#5]
The default k value is the dimensionality of the data points + 1

Is there a motivation behind this? I can see how it would fail if the dimensionality of the points is comparable or higher than the number of data points.

I would have rather made the option mandatory for the user of the library.

**Comment by targos** [comment]
@JeffersonH44

**Comment by stropitek** [comment]
ping @JeffersonH44

**Comment by JeffersonH44** [comment]
Ok, I will do that

**Comment by JeffersonH44** [comment]
solved #8
