### ISSUE TITLE
Saving KNN Model

### ISSUE THREAD

**Issue by joevbruno** [mljs/knn#6]
@maasencioh @targos what's the best way to save a trained model for later use?

**Comment by JeffersonH44** [comment]
we have to add that method to save the model, I will add it

**Comment by joevbruno** [comment]
@JeffersonH44 thanks! Do you know when you might be able to complete the task?  I expected to be able to save the modal JSON and reload it or have some kind of a `toJSON` / `fromJSON` or `download`/ 'import' function available. If that sounds reasonable and you can provide a little direction, I'm happy to submit a PR.

**Comment by maasencioh** [comment]
Hi @joevbruno. We discussed about it and implemented the feature.
You can now (in version 2.1.0) serialize the model to JSON using either `knn.toJSON()` (returns an object) or `JSON.stringify(knn)` and then reload it with `KNN.load(model)`.
Documentation: https://github.com/mljs/knn#tojson

**Comment by joevbruno** [comment]
@maasencioh Thank you so much for the quick response, additional feature, and fresh npm publish. You rock! And thanks for creating / maintaining this project!

**Comment by maasencioh** [comment]
@joevbruno well to be honest @JeffersonH44 already had this before, so it was teamwork, but thanks!
